### ISSUE TITLE
Unexpected "Cannot read property 'constructor' of null"

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/workbase#163] opened 2019-07-18 18:18 UTC
## Description

I receive `Unexpected "Cannot read property 'constructor' of null"` even though the query executes and renders the graph correctly.

## Environment

1. Grakn version: Grakn Core 1.5.6
2. OS of Grakn server: Mac OS 10
3. Workbase version: 1.2.2
4. OS of Workbase: Mac OS 10

## Reproducible Steps
1. Load the attached graql file: [genealogy.txt](https://github.com/graknlabs/workbase/files/3407877/genealogy.txt)
2. Run`match $x($y) isa parentship; get; offset 0; limit 200;` (no error)
3. Followed by `match $x($y) isa siblingship; get; offset 0; limit 200;`
4. See the error despite seemingly correct function. Note that this second query retrieves mostly inferred relations.
 
## Additional information
<img width="770" alt="Screenshot 2019-07-18 at 14 45 19" src="https://user-images.githubusercontent.com/38212943/61481576-7d0e8880-a990-11e9-9749-7876c0a1e676.png">

**Comment by sorsaffari** [comment] 2020-06-05 14:25
@jmsfltchr seems like this issue has been resolved, as I couldn't reproduce it. I suspect that the root cause was in `client-nodejs` and it's been fixed since the making this issue.

closing, but feel free to open it if you've recently faced this issue

**Closed by sorsaffari** 2020-06-05 14:25 UTC
Labels: type: bug
